apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imagereg-base
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: overlays/sealsec-overlay
    repoURL: https://github.com/maxisses/imagereg.git
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true