apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  registrySources:
    allowedRegistries:
    - registry.gitlab.com
    - quay.io
    - registry.redhat.io
    - image-registry.openshift-image-registry.svc:5000
    - '*.container.someone.com'
    - registry.connect.redhat.com
